Add docs for Redis on QingCloud
QingCloudAppcenter/user-guide pull request #10
Opened 2017-06-23 06:27 UTC by zryfish

Doc for Redis standalone on QingCloud

2017-06-23 06:40 UTC, rayzhou2017 requested changes
1. 获取日志用到了系统的密码，相当于主机对用户开放了，用户岂不是可以直接登录？有没有办法只有ftp用户的密码提供出来？
2. 迁移数据脚本能不能放个地方，让用户直接下载，然后告诉用户怎么用就可以了？用户看到一大堆代码第一反应会蒙的。

2017-06-23 10:09 UTC, zryfish commented
@rayzhou2017 按照建议的修改了，现在ftp_redis用户只能用作 ftp 下载使用，没有上传文件的权限，也没有登录主机的权限。 迁移脚本单独拿出来了，可以直接下载，增加了另一种迁移方法。

2017-06-23 10:31 UTC, rayzhou2017 requested changes
镜像的系统密码也要改一下，不能用默认密码。另外备份是不是也可以提供？可以下周上线。

2017-06-23 12:16 UTC, zryfish commented
@rayzhou2017 备份有个顾虑，因为enable config可能会导致master 和 slave 的配置不同，备份如果选择的节点是 slave 节点，那么 master 节点的配置就会丢失了

2017-06-26 07:14 UTC, rayzhou2017 approved these changes

2017-06-26 07:14 UTC, merged