Redis cluster
QingCloudAppcenter/user-guide pull request #18
Opened 2017-06-27 09:57 UTC by julykobe

add redis cluster doc

2017-06-28 07:09 UTC, rayzhou2017 requested changes
最大内存env没有加到截图里吧

2017-07-05 06:15 UTC, martinyunify commented
README.md应该是大写的，build里面文档生成失败了。可以点travis看结果

2017-07-05 06:19 UTC, martinyunify commented on SUMMARY.md
> +* [Redis Cluster](docs/redis-cluster/README.md)
这个链接不存在所以build报错

2017-07-05 06:33 UTC, julykobe commented on SUMMARY.md
> +* [Redis Cluster](docs/redis-cluster/README.md)
got it. 我改过来了在试试

2017-07-12 02:30 UTC, martinyunify commented
@rayzhou2017 可以合并吗

2017-07-12 02:41 UTC, rayzhou2017 requested changes
迁移部分格式有点乱，下载地址要提供。另外参数不提供config enable吗？比如像standalone的那样。

2017-07-12 06:44 UTC, rayzhou2017 submitted a review, later dismissed

2017-07-13 11:21 UTC, rayzhou2017 approved these changes

2017-07-13 11:21 UTC, merged