add docs for kubernetes app
QingCloudAppcenter/user-guide pull request #27
Opened 2017-07-13 11:05 UTC by martinyunify

2017-07-13 11:20 UTC, rayzhou2017 requested changes
截图不对，改完我再看看

2017-07-14 02:10 UTC, rayzhou2017 commented
文档还显得有些粗糙，第二步就跳到第六步了，再仔细检查一遍

2017-07-14 07:03 UTC, jolestar requested changes

2017-07-14 07:03 UTC, jolestar commented on docs/kubernetes/README.md
> +![](screenshot/屏幕快照1.png)
图片的名字最好修改下吧。

2017-07-14 07:03 UTC, jolestar commented on docs/kubernetes/README.md
> +* k8s应用使用青云提供的SDN2.0,创建的Pod都会绑定一个网卡，分配一个私网地址。这里可以设置所使用的私网ID，私网需要预先准备好．如(vxnet-xxxxxxx)
加上
------------
建议给 pod 设置专用的私网，每个私网可以容纳200多个 ip，如果您需要的容器数量较多，请填写多个，之间用空格切分。

2017-07-14 07:03 UTC, jolestar commented on docs/kubernetes/README.md
> +* k8s需要从dockerhub.qingcloud.com下载镜像包含青云定制的k8s服务镜像，因此需要用户填写docherhub.qingcloud.com用户名和密码。这个账户请用户提交工单进行申请
写当前需要提交工单申请，系统已经内置了 guest 账号，可以拉取 dockerhub.qingcloud.com 上的公开仓库。如果需要创建和使用自己的仓库，请提交工单申请。

2017-07-14 07:03 UTC, jolestar commented on docs/kubernetes/README.md
> +使用ubuntu/k8s 登录。执行
通过 root/k8s 登陆。

2017-07-14 07:03 UTC, jolestar commented on docs/kubernetes/README.md
> +同样，访问http://跳板机ip:8001/api/v1/proxy/namespaces/kube-system/services/kibana-logging/ 会打开日志服务的kibana
增加：

通过 kubectl cluster-info，可以查看其它服务的 proxy 地址。

2017-07-17 02:14 UTC, jolestar approved these changes
先发了让用户试用，再优化吧。

2017-07-18 09:07 UTC, rayzhou2017 requested changes
垂直扩容这个地方排版怎么弄不好？

2017-07-18 09:07 UTC, rayzhou2017 commented on docs/kubernetes/README.md
> +* k8s应用使用青云提供的SDN2.0,创建的Pod都会绑定一个网卡，分配一个私网地址。这里可以设置所使用的私网ID，私网需要预先准备好．如(vxnet-xxxxxxx)
是的，这个应该加上，这个地方用户体验稍微差了点，用户还要去copy vxnet ID，先这样吧

2017-07-19 02:56 UTC, rayzhou2017 approved these changes

2017-07-19 02:56 UTC, merged