Add collabora office docs
QingCloudAppcenter/user-guide pull request #95
Opened 2017-10-31 10:07 UTC by Xuanwo

2017-11-07 12:12 UTC, rayzhou2017 requested changes

2017-11-07 12:12 UTC, rayzhou2017 commented on SUMMARY.md
> +* [Collabora Online](docs/collabora-online/README.md)
这个跟NextCloud App是什么关系？

2017-11-07 12:12 UTC, rayzhou2017 commented on docs/collabora-office/README.md
> +# Nextcloud on QingCloud AppCenter 用户手册
Title是不是错了？还是 Nextcloud？

2017-11-07 12:12 UTC, rayzhou2017 commented on docs/collabora-office/README.md
> +Collabora Office 节点依赖于青云 QingCloud 提供的负载均衡器服务，我们需要创建资源并进行相应的设置。如果之前创建 NextCloud 集群时已经创建了负载均衡器，则只需要再创建一个监听器并监听不同端口即可。同样需要注意：
这个地方最好加上Nextcloud app的link，这样用户能快速地找到

2017-11-07 12:12 UTC, rayzhou2017 commented on docs/collabora-office/README.md
> +[Collabora Office](https://www.collaboraoffice.com/code/) 是一个开源的企业级文档协同编辑解决方案。
这个工具必须需要Nextcloud才能工作吗？

2017-11-08 05:17 UTC, Xuanwo commented on docs/collabora-office/README.md
> +[Collabora Office](https://www.collaboraoffice.com/code/) 是一个开源的企业级文档协同编辑解决方案。
不一定，只要支持 WOPI 接口就可以使用。

2017-11-08 05:18 UTC, Xuanwo commented on docs/collabora-office/README.md
> +# Nextcloud on QingCloud AppCenter 用户手册
Fixed.

2017-11-08 05:19 UTC, Xuanwo commented on docs/collabora-office/README.md
> +Collabora Office 节点依赖于青云 QingCloud 提供的负载均衡器服务，我们需要创建资源并进行相应的设置。如果之前创建 NextCloud 集群时已经创建了负载均衡器，则只需要再创建一个监听器并监听不同端口即可。同样需要注意：
Done.

2017-11-09 07:14 UTC, rayzhou2017 approved these changes

2017-11-09 07:51 UTC, merged